project:
  type: book
  output-dir: _book

book:
  title: "Policy Brief"
  author:
     - name: "Daniel Antal, CFA"
       orcid: 0000-0001-7513-6760
       affiliations:
               - name: Reprex
                 address: "Saturnusstraat 14"
                 city: The Hague
                 state: Zuid-Holland
                 country: The Netherlands
                 postal-code: "2516 AH"
                 url: https://reprex.nl/
  contributor:
     - name: "Mester, Anna Márta"
       role: "Contributor"
       orcid: 0000-0001-7513-6760
  date: "2024-06-09"
  repo-url: https://github.com/dataobservatory-eu/open-music-data-white-paper
  repo-actions: [edit]
  chapters:
    - index.qmd
    - glossary.qmd
    - context.qmd
    - curation.qmd
    - observatory.qmd
    - ai.qmd
    - conclusion.qmd
    - references.qmd

bibliography: 
    - bib/collections.bib
    - bib/ISOData.bib
    - bib/mme.bib
    - bib/musicmetadata.bib
    - bib/OpenMusE.bib
    - bib/wikidata.bib
    
csl: csl/chicago-author-date-17th-edition.csl

format:
  html:
    theme: cosmo
  docx: default
  pdf:
    documentclass: scrreprt
    papersize: a4            
    geometry: top=25mm, bottom=25mm, left=25mm, right=25mm
    fontsize: 12pt
  epub: default 

editor: visual

