project:
  type: book
  output-dir: _book
  
execute:
  freeze: auto

book:
  title: "A Green Paper on AI, Data Governance, and Metadata Policies for Europe’s Music Ecosystem"
  subtitle: "Practical Steps Towards a Decentralised and Open European Music Observatory"
  author:
     - name: "Daniel Antal, CFA"
       orcid: 0000-0001-7513-6760
       affiliations:
               - name: Reprex
                 address: "Saturnusstraat 14"
                 city: The Hague
                 state: Zuid-Holland
                 country: The Netherlands
                 postal-code: "2516 AH"
                 url: https://reprex.nl/
  contributor:
     - name: "Mester, Anna Márta"
       role: "Contributor"
       orcid: 0000-0001-7513-6760
  date: "2024-09-07"
  repo-url: https://github.com/dataobservatory-eu/open-music-data-white-paper
  repo-actions: [edit]
  chapters:
    - index.qmd
    - glossary.qmd
    - context.qmd
    - curation.qmd
    - observatory.qmd
    - ai.qmd
    - conclusion.qmd
    - references.qmd

citation:
  container-title: "Open Music Observatory"
  doi: "10.5281/zenodo.17075796"
  url: https://example.com/summarizing-output

bibliography: 
    - bib/BVDA.bib
    - bib/datainteroperability.bib
    - bib/dataspace.bib
    - bib/decolonisation.bib
    - bib/CISAC.bib
    - bib/collections.bib
    - bib/eulaw.bib
    - bib/eupolicies.bib
    - bib/europeana.bib
    - bib/eXtremeDesign.bib
    - bib/IFPI.bib
    - bib/ISOData.bib
    - bib/metadata.bib
    - bib/MLC.bib
    - bib/mme.bib
    - bib/musicmetadata.bib
    - bib/opendata.bib
    - bib/OpenMusE.bib
    - bib/trustworthyAI.bib
    - bib/wikidata.bib
    
csl: csl/chicago-author-date-17th-edition.csl

format:
  html:
    theme: cosmo
  docx: default
  pdf:
    documentclass: scrreprt
    papersize: a4            
    geometry: top=25mm, bottom=25mm, left=25mm, right=25mm
    fontsize: 12pt
  epub: default 

editor: visual

